# Form implementation generated from reading ui file 'numbas.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
# Solverkind is cool https://drive.google.com/file/d/1LzaShOt4HKqoOlAThObUHEjD6PR53_C7/view?usp=sharing
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess, os, sys

from PyQt6 import QtCore, QtGui, QtWidgets
import random as random
try:
    formf = subprocess.check_output('cat /etc/sandpotnoodles-formfactor', shell=True).decode('utf-8')
except:
    os.system('zenity --warning --text="Can\'t determine formfactor, run sudo sand-setplat"')
    sys.exit()

print(formf)

class Ui_Form(object):
    num = 1
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 354)
        if formf != 'desktop\n':
            Form.resize(400, 733)
        if formf == 'tv\n':
            Form.showFullScreen()
        Form.setMinimumSize(QtCore.QSize(376, 311))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));\n"
                           "color: rgb(255, 255, 255);\n"
                           "border-color: rgb(48, 48, 48);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
            self.pushButton_5.setMinimumSize(QtCore.QSize(0, 34))
            self.pushButton_5.setObjectName("pushButton_5")
            self.verticalLayout.addWidget(self.pushButton_5)
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 251))
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(12)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber.setProperty("intValue", 1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        if formf == 'desktop\n':
            self.spinBox = QtWidgets.QSpinBox(parent=self.frame_2)
            self.spinBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
            self.spinBox.setMinimum(-10000000)
            self.spinBox.setMaximum(100000000)
            self.spinBox.setProperty("value", 1)
            self.spinBox.setObjectName("spinBox")
            self.horizontalLayout_2.addWidget(self.spinBox)
        elif formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("../../Downloads/Frame 80.png"), QtGui.QIcon.Mode.Normal,
                           QtGui.QIcon.State.Off)
            self.open_kb = QtWidgets.QPushButton(parent=self.frame_2)
            self.open_kb.setMinimumSize(QtCore.QSize(0, 58))
            self.open_kb.setDefault(False)
            self.open_kb.setObjectName("open_kb")
            self.horizontalLayout_2.addWidget(self.open_kb)
            self.open_kb.setStyleSheet(
                "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));\n"
                "color: rgb(255, 255, 255);\n"
                "border-color: rgb(48, 48, 48);")
            self.down = QtWidgets.QPushButton(parent=self.frame_2)
            self.down.setMinimumSize(QtCore.QSize(0, 58))
            self.down.setMaximumSize(QtCore.QSize(75, 16777215))
            self.down.setIcon(icon)
            self.down.setIconSize(QtCore.QSize(60, 60))
            self.down.setObjectName("down")
            self.down.setStyleSheet(
                "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));\n"
                "color: rgb(255, 255, 255);\n"
                "border-color: rgb(48, 48, 48);")
            self.horizontalLayout_2.addWidget(self.down)
            self.up = QtWidgets.QPushButton(parent=self.frame_2)
            self.up.setMinimumSize(QtCore.QSize(0, 58))
            self.up.setMaximumSize(QtCore.QSize(75, 16777215))
            self.up.setText("")
            icon1 = QtGui.QIcon()
            icon1.addPixmap(QtGui.QPixmap("../../Downloads/Frame 81.png"), QtGui.QIcon.Mode.Normal,
                            QtGui.QIcon.State.Off)
            self.up.setIcon(icon1)
            self.up.setIconSize(QtCore.QSize(60, 60))
            self.up.setObjectName("up")
            self.horizontalLayout_2.addWidget(self.up)
            self.up.setStyleSheet(
                "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));\n"
                "color: rgb(255, 255, 255);\n"
                "border-color: rgb(48, 48, 48);")
        #self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        #self.pushButton_5.setMaximumSize(QtCore.QSize(95, 16777215))
        #if formf == 'desktop\n':
        #    self.pushButton_5.setMinimumSize(QtCore.QSize(0,0))
        #elif formf == 'mobile\n' or 'tablet':
        #    self.pushButton_5.setMinimumSize(QtCore.QSize(0,55))
        #    self.frame_2.setMinimumSize(QtCore.QSize(0,72))
        #self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
        #self.pushButton_5.setObjectName("pushButton_5")
        #self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Frame 75.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(41, 41))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/Frame 74.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(41, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/Frame 77.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(41, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 51))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/Frame 76.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(41, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame)
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.keyboard = QtWidgets.QFrame(parent=Form)
            self.keyboard.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.keyboard.setStyleSheet(
                "background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(47, 47, 47, 255));\n"
                "color: rgb(255, 255, 255);")
            self.keyboard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
            self.keyboard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
            self.keyboard.setObjectName("keyboard")
            self.gridLayout = QtWidgets.QGridLayout(self.keyboard)
            self.gridLayout.setObjectName("gridLayout")
            self.key6 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key6.sizePolicy().hasHeightForWidth())
            self.key6.setSizePolicy(sizePolicy)
            self.key6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key6.setObjectName("key6")
            self.gridLayout.addWidget(self.key6, 1, 2, 1, 1)
            self.key2 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key2.sizePolicy().hasHeightForWidth())
            self.key2.setSizePolicy(sizePolicy)
            self.key2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key2.setObjectName("key2")
            self.gridLayout.addWidget(self.key2, 0, 1, 1, 1)
            self.key4 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key4.sizePolicy().hasHeightForWidth())
            self.key4.setSizePolicy(sizePolicy)
            self.key4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key4.setObjectName("key4")
            self.gridLayout.addWidget(self.key4, 1, 0, 1, 1)
            self.key7 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key7.sizePolicy().hasHeightForWidth())
            self.key7.setSizePolicy(sizePolicy)
            self.key7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key7.setObjectName("key7")
            self.gridLayout.addWidget(self.key7, 2, 0, 1, 1)
            self.key1 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key1.sizePolicy().hasHeightForWidth())
            self.key1.setSizePolicy(sizePolicy)
            self.key1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key1.setObjectName("key1")
            self.gridLayout.addWidget(self.key1, 0, 0, 1, 1)
            self.key5 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key5.sizePolicy().hasHeightForWidth())
            self.key5.setSizePolicy(sizePolicy)
            self.key5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key5.setObjectName("key5")
            self.gridLayout.addWidget(self.key5, 1, 1, 1, 1)
            self.key8 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key8.sizePolicy().hasHeightForWidth())
            self.key8.setSizePolicy(sizePolicy)
            self.key8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key8.setObjectName("key8")
            self.gridLayout.addWidget(self.key8, 2, 1, 1, 1)
            self.key3 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key3.sizePolicy().hasHeightForWidth())
            self.key3.setSizePolicy(sizePolicy)
            self.key3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key3.setObjectName("key3")
            self.gridLayout.addWidget(self.key3, 0, 2, 1, 1)
            self.key9 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key9.sizePolicy().hasHeightForWidth())
            self.key9.setSizePolicy(sizePolicy)
            self.key9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key9.setObjectName("key9")
            self.gridLayout.addWidget(self.key9, 2, 2, 1, 1)
            self.backspace = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.backspace.sizePolicy().hasHeightForWidth())
            self.backspace.setSizePolicy(sizePolicy)
            self.backspace.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.backspace.setObjectName("backspace")
            self.gridLayout.addWidget(self.backspace, 3, 0, 1, 1)
            self.key0 = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.key0.sizePolicy().hasHeightForWidth())
            self.key0.setSizePolicy(sizePolicy)
            self.key0.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.key0.setObjectName("key0")
            self.gridLayout.addWidget(self.key0, 3, 1, 1, 1)
            self.done = QtWidgets.QPushButton(parent=self.keyboard)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum,
                                               QtWidgets.QSizePolicy.Policy.Minimum)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.done.sizePolicy().hasHeightForWidth())
            self.done.setSizePolicy(sizePolicy)
            self.done.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
            self.done.setObjectName("done")
            self.gridLayout.addWidget(self.done, 3, 2, 1, 1)
            self.verticalLayout.addWidget(self.keyboard)

        self.retranslateUi(Form)
        if formf == 'desktop\n':
            self.spinBox.valueChanged['int'].connect(self.changenum) # type: ignore
        elif formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.open_kb.clicked.connect(self.keyboard.show)  # type: ignore
            self.pushButton_5.clicked.connect(sys.exit)
        self.pushButton.clicked.connect(self.lcdNumber.setDecMode) # type: ignore
        self.pushButton_2.clicked.connect(self.lcdNumber.setBinMode) # type: ignore
        self.pushButton_3.clicked.connect(self.lcdNumber.setHexMode) # type: ignore
        self.pushButton_4.clicked.connect(self.lcdNumber.setOctMode) # type: ignore
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.done.clicked.connect(self.keyboard.hide)  # type: ignore
            self.open_kb.clicked.connect(self.keyboard.show)  # type: ignore
            self.pushButton.setMinimumSize(QtCore.QSize(0, 73))
            self.pushButton_2.setMinimumSize(QtCore.QSize(0, 73))
            self.pushButton_3.setMinimumSize(QtCore.QSize(0, 73))
            self.pushButton_4.setMinimumSize(QtCore.QSize(0, 73))
            self.up.clicked.connect(self.goup)
            self.down.clicked.connect(self.godown)
        QtCore.QMetaObject.connectSlotsByName(Form)
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.key0.clicked.connect(self.kA)
            self.key1.clicked.connect(self.kB)
            self.key2.clicked.connect(self.bC)
            self.key3.clicked.connect(self.bD)
            self.key4.clicked.connect(self.bE)
            self.key5.clicked.connect(self.bF)
            self.key6.clicked.connect(self.bG)
            self.key7.clicked.connect(self.bH)
            self.key8.clicked.connect(self.bI)
            self.key9.clicked.connect(self.bJ)
            self.backspace.clicked.connect(self.bk)
            self.keyboard.hide()
    def changenum_mobile(self, change):
        self.num = change
        self.lcdNumber.display(self.num)
        _translate = QtCore.QCoreApplication.translate
        self.open_kb.setText(_translate("Form", str(self.num)))
    def goup(self):
        try:
            self.changenum_mobile(self.num + 1)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def godown(self):
        try:
            self.changenum_mobile(self.num - 1)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def kA(self):
        try: self.changenum_mobile((self.num * 10))
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def kB(self):
        try: self.changenum_mobile((self.num * 10)+1)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bk(self):
        if len(str(self.num)) > 1:
            try: self.changenum_mobile(int(str(self.num)[1:]))
            except:
                os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bC(self):
        try: self.changenum_mobile((self.num * 10)+2)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bD(self):
        try: self.changenum_mobile((self.num * 10)+3)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bE(self):
        try: self.changenum_mobile((self.num * 10)+4)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bF(self):
        try: self.changenum_mobile((self.num * 10)+5)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bG(self):
        try: self.changenum_mobile((self.num * 10)+6)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bH(self):
        try: self.changenum_mobile((self.num * 10)+7)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bI(self):
        try: self.changenum_mobile((self.num * 10)+8)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def bJ(self):
        try: self.changenum_mobile((self.num * 10)+9)
        except:
            os.system("zenity --warning --text=\"Reaced Number Limit\"")
    def changenum(self, numa):
        self.lcdNumber.display(numa)
    def rand(self):
        self.spinBox.setProperty("Value", random.randint(-100000, 100000))
        self.lcdNumber.display(self.spinBox.value())
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Diginum"))
        #self.pushButton_5.setText(_translate("Form", "Randomize"))
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            print('mobile moment')
            print(formf)

        self.pushButton.setText(_translate("Form", "DEC"))
        self.pushButton_2.setText(_translate("Form", "BIN"))
        self.pushButton_3.setText(_translate("Form", "HEX"))
        self.pushButton_4.setText(_translate("Form", "OCT"))
        if formf == 'mobile\n' or formf == 'tablet' or formf == 'tv\n':
            self.pushButton_5.setText(_translate("Form", "Exit"))
            self.open_kb.setText(_translate("Form", "1"))
            self.open_kb.setText(_translate("Form", "1"))
            self.key6.setText(_translate("Form", "6"))
            self.key2.setText(_translate("Form", "2"))
            self.key4.setText(_translate("Form", "4"))
            self.key7.setText(_translate("Form", "7"))
            self.key1.setText(_translate("Form", "1"))
            self.key5.setText(_translate("Form", "5"))
            self.key8.setText(_translate("Form", "8"))
            self.key3.setText(_translate("Form", "3"))
            self.key9.setText(_translate("Form", "9"))
            self.backspace.setText(_translate("Form", "<-"))
            self.key0.setText(_translate("Form", "0"))
            self.done.setText(_translate("Form", "Done"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
