# Form implementation generated from reading ui file 'sand-setplat.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os, sys, subprocess

usr = f'/usr/share/sandpotnoodles/'

no_override = False
if len(sys.argv) > 1:
        if sys.argv[1] == '--no-override':
                no_override = True
if os.getuid() != 0:
        print("mate run this as root i need to modify or create /etc/sandpotnoodles-formfactor")
        os.system(f'zenity --info --text="mate run this as root i need to modify or create /etc/sandpotnoodles-formfactor"')
        sys.exit()
if os.path.exists('/etc/sandpotnoodles-formfactor'):
        if no_override:
                print("Aready created formfactor config so that'll be skipped")
                sys.exit()
        print('The formfactor configuration file already exists so it\'ll be overwritten btw')
        os.system(f'zenity --info --text="The formfactor configuration file already exists so it\'ll be overwritten btw"')
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(617, 648)
        Form.setMinimumSize(QtCore.QSize(617, 648))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.555556 rgba(56, 56, 56, 255), stop:0.816425 rgba(115, 115, 115, 255), stop:1 rgba(91, 91, 91, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(f"{usr}sandpotnoodles-logo-small.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 94))
        self.pushButton.setMaximumSize(QtCore.QSize(588, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{usr}tv.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(151, 151))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.desktop = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desktop.sizePolicy().hasHeightForWidth())
        self.desktop.setSizePolicy(sizePolicy)
        self.desktop.setMinimumSize(QtCore.QSize(0, 94))
        self.desktop.setMaximumSize(QtCore.QSize(588, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.desktop.setFont(font)
        self.desktop.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{usr}desktop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.desktop.setIcon(icon1)
        self.desktop.setIconSize(QtCore.QSize(151, 151))
        self.desktop.setObjectName("desktop")
        self.gridLayout.addWidget(self.desktop, 1, 0, 1, 1)
        self.mobile = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mobile.sizePolicy().hasHeightForWidth())
        self.mobile.setSizePolicy(sizePolicy)
        self.mobile.setMinimumSize(QtCore.QSize(0, 94))
        self.mobile.setMaximumSize(QtCore.QSize(588, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.mobile.setFont(font)
        self.mobile.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(91, 91, 91, 255));")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{usr}mobile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mobile.setIcon(icon2)
        self.mobile.setIconSize(QtCore.QSize(151, 151))
        self.mobile.setObjectName("mobile")
        self.gridLayout.addWidget(self.mobile, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.desktop.clicked.connect(self.desk)
        self.mobile.clicked.connect(self.mob)
        self.pushButton.clicked.connect(self.television)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def done(self):
            os.system(f'zenity --info --text="Set formfactor successfully"')
            os.system(f'zenity --info --text="If you want to change it, run the following command as root: \'sand-setplat\'"')
            os.system(f'zenity --info --text="(note that you may have to install it again)"')
    def desk(self):
            Form.close()
            os.system("rm -f /etc/sandpotnoodles-formfactor; echo 'desktop' | tee '/etc/sandpotnoodles-formfactor'")
            self.done()
    def mob(self):
            Form.close()
            os.system("rm -f /etc/sandpotnoodles-formfactor; echo 'mobile' | tee '/etc/sandpotnoodles-formfactor'")
            self.done()
    def television(self):
            Form.close()
            os.system("rm -f /etc/sandpotnoodles-formfactor; echo 'tv' | tee '/etc/sandpotnoodles-formfactor'")
            self.done()
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Set Device Formfactor (MintMix/SandPotNoodles)")
        self.label_2.setText(_translate("Form", "Formfactor Selection"))
        self.pushButton.setText(_translate("Form", "TV"))
        self.label_3.setText(_translate("Form", "idk how to tell automaticly (and accuratly) so can you select it mate thanks"))
        self.desktop.setText(_translate("Form", "Desktop"))
        self.mobile.setText(_translate("Form", "Mobile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
